[package]
name = "cjseq"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.*", features = ["cargo"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# serde_derive = "1.0"


